### https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: my-azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
parameters:
    skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-azurefile
spec:
    accessModes:
    - ReadWriteMany
    storageClassName: azurefile
    resources:
        requests:
          storage: ${PVC_SIZE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatlingnode
spec:
  selector:
    matchLabels:
        app: gatlingnode
        version: v1
  replicas: ${NUM_OF_NODES}
  template:
    metadata:
      labels:
        app: gatlingnode
        version: v1
    spec:
      containers:
        - image: ${DOCKERHUB_NODE_IMAGE}
          imagePullPolicy: Always
          name: gatlingnode
          resources:
            requests:
              memory: ${NODE_MEMORY_REQUEST}
              cpu: ${NODE_CPU_REQUEST}
            limits:
              memory: ${NODE_MEMORY_LIMIT}
              cpu: ${NODE_CPU_LIMIT}
          volumeMounts:
            - name: copied-run-files
              mountPath: ${GATLING_COPIED_DIR}
            - name: pvc-data
              mountPath: /pvc-data
          env:
            - name: LOAD_PROFILE_NAME
              value: "${LOAD_PROFILE_NAME}"
      volumes:
        - name: copied-run-files
          configMap:
            name: ${CONFIGMAP_LOAD_PROFILE}
            items:
            - key: "${K8SPROPERTIES}"
              path: "${K8SPROPERTIES}"
            - key: "${LOAD_PROFILE_SCALA}"
              path: "${LOAD_PROFILE_SCALA}"
            - key: "${LOAD_PROFILE_JSON}"
              path: "${LOAD_PROFILE_JSON}"
        - name: pvc-data
          persistentVolumeClaim:
            claimName: my-azurefile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatlingjoiner
spec:
  selector:
    matchLabels:
        app: gatlingjoiner
        version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: gatlingjoiner
        version: v1
    spec:
      containers:
        - image: ${DOCKERHUB_JOINER_IMAGE}
          imagePullPolicy: Always
          name: gatlingjoiner
          resources:
            requests:
                memory: ${JOINER_MEMORY_REQUEST}
                cpu: ${JOINER_CPU_REQUEST}
            limits:
                memory: ${JOINER_MEMORY_LIMIT}
                cpu: ${JOINER_CPU_LIMIT}
          volumeMounts:
            - name: copied-run-files
              mountPath: ${GATLING_COPIED_DIR}
            - name: pvc-data
              mountPath: /pvc-data
          env:
            - name: LOAD_PROFILE_NAME
              value: "${LOAD_PROFILE_NAME}"
            - name: NUM_OF_NODES
              value: "${NUM_OF_NODES}"
      volumes:
        - name: copied-run-files
          configMap:
            name: ${CONFIGMAP_LOAD_PROFILE}
            items:
            - key: "${K8SPROPERTIES}"
              path: "${K8SPROPERTIES}"
            - key: "${LOAD_PROFILE_SCALA}"
              path: "${LOAD_PROFILE_SCALA}"
            - key: "${LOAD_PROFILE_JSON}"
              path: "${LOAD_PROFILE_JSON}"
        - name: pvc-data
          persistentVolumeClaim:
            claimName: my-azurefile
            
