apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatlingcluster
spec:
  selector:
    matchLabels:
        app: gatlingcluster
        version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: gatlingcluster
        version: v1
    spec:
      containers:
        - image: registry.hub.docker.com/jibijose/gatlingcluster:latest
          imagePullPolicy: Always
          name: gatlingcluster
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
            - name: config
              mountPath: /gatling_run_dir/gatling-charts-highcharts-bundle-3.3.1/copied-run-files
      volumes:
        - name: config
          configMap:
            name: cm.gatling
            items:
            - key: "loadprofile.scala"
              path: "loadprofile.scala"
