apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatlingcluster
spec:
  selector:
    matchLabels:
        app: gatlingcluster
        version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: gatlingcluster
        version: v1
    spec:
      containers:
        - image: registry.hub.docker.com/jibijose/inprogress:latest
          imagePullPolicy: Always
          name: gatlingcluster
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
          startupProbe:
            exec:
                command:
                - cat
                - /gatling_run_dir/gatling-charts-highcharts-bundle-3.3.1/conf/gatling-akka.conf
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
                command:
                - cat
                - /gatling_run_dir/gatling-charts-highcharts-bundle-3.3.1/conf/gatling-akka.conf
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
                command:
                - cat
                - /gatling_run_dir/gatling-charts-highcharts-bundle-3.3.1/conf/gatling-akka.conf
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /gatling_run_dir/gatling-charts-highcharts-bundle-3.3.1/copied-run-files
      volumes:
        - name: config
          configMap:
            name: cm.gatling
            items:
            - key: "loadprofile.scala"
              path: "loadprofile.scala"
